bbc/storyplayer

package.json, src/gui/Player.js, src/renderers/BaseRenderer.js, src/renderers/BaseTimedMediaRenderer.js
There was a bug where trimmed media continued playing during an end pause behaviour.  This is a fix. 
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3359
=> fix: pause properly with trimmed media

.jenkins/Dockerfile
Allows the Docker process for Jenkins to use a more recent version of node, fixing a build issue and slightly future proofing it. 
=> chore: update node version for Jenkins builds

package.json, src/RenderManager.js
Adds an additional check to ensure we do not delete the current renderer when tidying unused ones up.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3418
=> fix: do not delete renderer that is in use

.jenkins/Dockerfile
Sets `/var/tmp/jenkins` to be globally read/write, allowing the user with id 999 to write to it
Ticket / issue URL:  https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3422
=> fix: allow any user to write to jenkins user home dir within the container

package.json, src/behaviours/TextOverlayBehaviourHelper.js
Allows the string for a text overlay behaviour to be HTML and to render it, although `<script>` tags and their content should be stripped.  This should allow much more flexibilty - new lines, headings, bold, better styling, etc.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3449
=> feat: enable html tags in text overlay behaviours, except script

package.json, src/assets/styles/player.scss, src/gui/Player.js
Does not highlight focused choice by default; highlighting only appears when keyboard is used, and disappears after 2s of keyboard inactivity.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3445
=> fix: only render choice focus outlines when keyboard is active

package.json, src/behaviours/VariableManipulateBehaviour.js
Boolean manipulation was failing because we check the truthiness of a jsonlogic operation.  This is unnecessary as json logic throws an error if the operation expression is invalid.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3455
=> fix: remove unnecessary check on jsonlogic

package.json, src/renderers/BackgroundAudioRenderer.js, src/renderers/BaseTimedMediaRenderer.js, src/renderers/ImageRenderer.js, src/renderers/SimpleAudioRenderer.js, src/renderers/SimpleTextRenderer.js, src/renderers/StoryIconRenderer.js, src/renderers/SwitchableRenderer.js, src/renderers/ThreeJsImageRenderer.js
Sends the `includeCredentials` option to the media resolver so we can use from within SMP plugin
https://github.com/bbc/rd-ux-media-resolver/blob/c959a5246034cd9acde56df75eebce229003b75c/src/ipStudio.js#L18
=> fix: uses credentials when resolving media

package.json, src/playoutEngines/SMPPlayoutEngine.js, src/renderers/BaseTimedMediaRenderer.js
Fixes the problem that EBU-TT subtitles are not playable before publishing.
The problem was that upload-ingest and the media resolver return a filename that doesn't have a `.xml` extension; which was used to distinguish VTT subs (suitable only for our player) and EBU-TT-D (required for SMP playout).  This fix takes the clumsy approach of fetching the file and inspecting the content.
Note that when media is published, this `captionsUrl` is not respected; the subs need publishing through galileo too.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3528
=> fix: inspects subtitles file contents to determine format

package.json, src/renderers/BaseRenderer.js, src/renderers/ImageRenderer.js
Fade in/out on image elements can show glitches - the image can flash up before fade-in starts or after fade-out finishes.  This tweaks the timing of calls in `start()` to fix these.
=> fix: tweaks renderer start to stop fade glitches

package.json, src/assets/styles/colours.scss, src/assets/styles/player.scss, src/assets/styles/px.scss, src/gui/Player.js
Adds some styling to allow link choices to be styled in the way the PX/UX team have designed [see Figma](https://www.figma.com/file/EMgGNvuIqIbYBjcGKiHxw1/PX_UI?node-id=2657%3A3398).
Mostly CSS, but adds a little code to set classes as choices are focused.
To actually apply, will need SPH to take a parameter from the plugin config and set a class on the `playerInteface.container`.
Testing: [here's a story](https://storyplayer-test.pilots.bbcconnectedstudio.co.uk/private/deed259a-811a-435f-a672-bae84ff42aa1) you can use (but might be good to test with more links, and with SMP player).  Code will only work with up to 10 links.  You will also need to manually add the `px` class to one of the higher level elements (e.g., the `div` that has the `romper-target` class).
Note that PX screen is …
=> feat: styles link choices to support PX work

package.json, src/gui/Player.js, src/playoutEngines/DOMSwitchPlayoutEngine.js, src/renderers/BaseRenderer.js
Fixes a bug introduced when started behaviours were removed: the controls hidden during a choice, but not made available again on the next element.
Also removes some more started behaviour code that is no longer needed and clears a console error that arose from the playout engine when starting up the experience
Ticket / issue URL:  https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3645
=> fix: fixes bug where controls not shown on element after choice

package.json, src/playoutEngines/DOMSwitchPlayoutEngine.js
Subtitles button wasn't showing at the right times.  Fixes.  [Test story](https://storyplayer-test.pilots.bbcconnectedstudio.co.uk/private/fb67d05d-9372-4e85-a37e-3ef501ff4031) has WebVTT subs on second element (note that the player does not distinguish what type of subs are available, so it sees that there are some in Element 1, but can't render them).
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3766
=> fix: corrects test for subtitle availability

package.json, src/RenderManager.js, src/renderers/BaseRenderer.js, src/renderers/BaseTimedIntervalRenderer.js, src/renderers/BaseTimedMediaRenderer.js, src/renderers/ImageRenderer.js, src/renderers/SimpleAudioRenderer.js, src/renderers/SimpleTextRenderer.js, src/renderers/SwitchableRenderer.js, src/renderers/ThreeJsImageRenderer.js, src/renderers/ThreeJsVideoRenderer.js
After removing `willStart` with the started behaviours, the full `start()` code of the renderers was being run multiple times while waiting for the `init()` to complete.  This fixes the code so that the main functionality in `start()` is only run once `init()` has completed
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3767
=> fix: corrects renderer start process

package.json, src/RenderManager.js, src/behaviours/PauseBehaviour.js, src/renderers/BaseRenderer.js
* Completed behaviours now run.  They had stopped when we removed during behaviours because the behaviour runner was initiated in the starting code.
* Implemented `pause` behaviour as a during behaviour.  Note that it cannot work as before in tandem with a show image or other during behaviours, as the timings of these are based on playhead time, so a pause of 2s at 2s will pause at 2s for 2s, but a parallel showimage of 2s with duration 2s will start at 2s but only disappear when the playhead reaches 4s.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3768
=> fix: sorts out some behaviour problems

package.json, webpack.config.js, yarn.lock
Fixes the webpack config so that images are stored in the dist/images folder with original filenames.  Uses new [Asset Modules](https://webpack.js.org/guides/asset-modules/) and removes `file-loader`.
Version bumped to `1.1.49`
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3779
=> fix: corrects webpack image file handling

src/playoutEngines/SMPPlayoutEngine.js
I'm not sure where the SMPPlayoutEngine is executing from, either in the top level window, or an iFrame, so I don't know if it should be `parent.location` or `window.location` - any guidance would be appreciated
Brief description of what this PR does. 
=> Fix: Try and get aroud CORS issue when requesting unpublished TTML subtitles

package.json, src/renderers/ThreeJSDriver.js
Removes uses of the deprecated `THREE.Math.degToRad`, and does the calculations manually
Ticket / issue URL:  https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3802
=> fix: replaces deprecated deg to rad conversion to fix 360 playback

package.json, src/gui/Player.js, src/playoutEngines/DOMSwitchPlayoutEngine.js, src/playoutEngines/SMPPlayoutEngine.js, src/playoutEngines/iOSPlayoutEngine.js
In SMP player, restart (from saved state) did not work with timed images.  This meant that Out Late did not work on the second (or subsequent) play through on PX.  This is a fix
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3806
=> fix: starts when ui enabled as long as renderer constructed

yarn.lock
Updates the lockfile references to the public NPM registry rather than BBC artifactory
=> fix: replace bbc artifactory references with npm registry

src/playoutEngines/SMPPlayoutEngine.ts
Removes reliance on parent.location when running SMP in an iFrame.
=> fix: replace parent.location usage

README.md, docker-compose.yml, examples/main.js, package-lock.json, package.json, src/storyplayer.ts, src/types/image.d.ts, src/types/index.d.ts, tsconfig.json, vite.config.js
- Changes to Vite JS to build as ES Modules
- Addition of docker compose to bring storyplayer up in watch mode
- Re-do exports from Storyplayer - THIS CHANGES THE DEFAULT EXPORT OF STORYPLAYER (so will need updating in SPH and SF)
- Spin up this build in watch mode using `docker compose up`
- Check out https://github.com/bbc/rd-ux-storyplayer-harness/pull/321
- Spin up SPH using `docker compose up` (**NOTE**: the `npm install` in the docker compose file will wipe out any `npm link` commands. So replace "npm install" with "npm link:storyplayer" to get it linked up and working as expected)
=> feat: default export as esmodule

package.json, src/gui/Player.ts, src/utils.ts
Prevents SMP plugin from throwing a console error in Chrome, since window.location cannot be used within iframe.
I've only been able to test that the `noUi=true` query parameter still works, as I can't bring up a local SPH instance with a local SP linked.
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-3980
=> fix: remove location.search calls from SMP plugin

package-lock.json, package.json, src/playoutEngines/DOMSwitchPlayoutEngine.ts
Adds the recent shaka player feature `preload` to the DOM player engine, used for DASH and non-native HLS. The preload step fetches further media segments, ahead of playback, than a default load resulting in a better transition between media. 
Fairly easy win as story objects already contains and loads the next media in the narrative before playback, so preloading is a  limited but impactful code change.
Also includes shaka-player version bump to 4.10.8
Ticket / issue URL: https://jira.dev.bbc.co.uk/browse/PRODTOOLS-4027
=> feat: add shaka preload

.github/workflows/build.yaml, README.md, docker-compose.yml, package-lock.json, package.json
Node 16 is EOL, this bumps the build image and github action workflows to 18 and 20.
https://jira.dev.bbc.co.uk/browse/PRODTOOLS-4144
https://jira.dev.bbc.co.uk/browse/PRODTOOLS-4020
=> chore: upgrade nodejs to maintenance and lts (18 and 20)
